jdk: oraclejdk8

language: java

services:
    - docker

sudo: required

install:
    - echo "HOLA"
    - docker login --username ${DOCKER_USER} --password ${DOCKER_PWD} 
    - docker build . -t "${PWD##*/}"
    - docker tag "${PWD##*/}" cgoncas/"${PWD##*/}"

script:
    - docker push cgoncas/"${PWD##*/}"
