jdk: oraclejdk8

language: java

services:
    - docker

sudo: required

install:
    - docker login --username ${DOCKER_USER} --password ${DOCKER_PWD}
    - docker build . -t "${PWD##*/}"
    - docker tag "${PWD##*/}" cgoncas/"${PWD##*/}"
    - docker tag "${PWD##*/}" cgoncas/"${PWD##*/}":`date +%Y%m%d%H%M%S`

script:
    - docker push cgoncas/"${PWD##*/}"
